# Training parameters

# file paths
save_dir: "./test/achilles/"
pretrained_model_dir: "./achilles/pretrain"
data_dir: "../Achilles_Classification/roi_data/"
metadata_csv: "../Achilles_Classification/roi_data/mil_metadata.csv"
     
# data loading
loader_kwargs:
    batch_size: 15
    num_workers: 8
res: 224 # height and width
    
# model
net_kwargs:
    num_heads: 1
    num_out: 1
    pooling_method: 'attn'
    drop_rate: 0.0
    debug: False

# encoder
encoder_kwargs:
    model_name: 'resnet50d'
    pretrained: True
    in_chans: 1
    num_classes: 1
    drop_rate: 0.0
    
# training
mil: True
num_epochs: 30
optim_kwargs:
    lr: 1.e-3
    weight_decay: 1.e-3
sched_kwargs:
    step_size: 8
    gamma: 0.1
verbose: False
pretrain_enc: True
pretrain_fc: True
freeze_enc: False
freeze_fc: False
folds: 10