# Training parameters

# file paths
save_dir: "./test/ct/"
pretrained_model_dir: "./ct/pretrain"
data_dir: "../CT/data/"
metadata_csv: "../CT/ct_metadata.csv"
     
# data loading
loader_kwargs:
    batch_size: 1
    num_workers: 8
res: 224 # height and width
    
# model
net_kwargs:
    num_heads: 1
    num_out: 1
    pooling_method: 'attn'
    drop_rate: 0.0
    debug: False

# encoder
encoder_kwargs:
    model_name: 'resnet50d'
    pretrained: True
    in_chans: 1
    num_classes: 1
    drop_rate: 0.2
    
# training
mil: True
num_epochs: 10
optim_kwargs:
    lr: 1.e-3
    weight_decay: 5.e-3
sched_kwargs:
    step_size: 50
    gamma: 0.1
verbose: False
pretrain_enc: False
pretrain_fc: False
freeze_enc: False
freeze_fc: False
folds: 10