# Training parameters

# file paths
save_dir: "./ct/pretrain"
data_dir: "../CT/data/"
metadata_csv: "../CT/ct_metadata.csv"
     
# data loading
loader_kwargs:
    batch_size: 50 
    num_workers: 8
res: 224 # height and width

# encoder
encoder_kwargs:
    model_name: 'resnet50d'
    pretrained: True
    in_chans: 1
    num_classes: 1
    drop_rate: 0.2
    
# training
mil: False
num_epochs: 10
optim_kwargs:
    lr: 1.e-3
    weight_decay: 5.e-3
sched_kwargs:
    step_size: 50
    gamma: 0.1
verbose: False
pretrain: False
freeze_enc: False
freeze_fc: False
folds: 10