# Training parameters

# file paths
save_dir: "./xray/pretrain"
data_dir: "../Xray/data/"
metadata_csv: "../Xray/images.csv"
targets_csv: "../Xray/targets.csv"
     
# data loading
loader_kwargs:
    batch_size: 75 
    num_workers: 4
res: 224 # height and width

# encoder
encoder_kwargs:
    model_name: 'resnet50d'
    pretrained: True
    in_chans: 1
    num_classes: 3
    drop_rate: 0.0
    
# training
mil: False
view_filter: ['AP_LIKE', 'Y']
num_epochs: 50
optim_kwargs:
    lr: 1.e-3
    weight_decay: 1.e-3
sched_kwargs:
    step_size: 50
    gamma: 0.1
verbose: False
pretrain: False
freeze_enc: False
freeze_fc: False
folds: 10