# Training parameters

# file paths
save_dir: "./test/xray/"
pretrained_model_dir: "./xray/pretrain"
data_dir: "../Xray/data/"
metadata_csv: "../Xray/images.csv"
targets_csv: "../Xray/targets.csv"
     
# data loading
loader_kwargs:
    batch_size: 25 
    num_workers: 8
res: 224 # height and width
    
# model
net_kwargs:
    num_heads: 1
    num_out: 3
    pooling_method: 'attn'
    drop_rate: 0.0
    debug: False

# encoder
encoder_kwargs:
    model_name: 'resnet50d'
    pretrained: True
    in_chans: 1
    num_classes: 3
    drop_rate: 0.3
    
# training
mil: True
view_filter: ['AP_LIKE', 'Y']
num_epochs: 50
optim_kwargs:
    lr: 1.e-3
    weight_decay: 1.e-3
sched_kwargs:
    step_size: 5
    gamma: 0.1
verbose: False
pretrain_enc: False
pretrain_fc: False
freeze_enc: False
freeze_fc: False
folds: 10